config/routes.rb
Rails.application.routes.draw do

#show all
get 'tasks', to: 'tasks#index'

#create
post 'tasks', to: 'tasks#create'
get 'tasks/new', to: 'tasks#new', as: :new_task

#read one
get 'tasks/:id', to: 'tasks#show', as: :task


#update
get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
patch 'tasks/:id', to: 'tasks#update'

#destroy
delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  # def set_task
  #   @task = Task.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>




  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a new task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<!-- app/views/tasks/index.html.erb -->
<ul>
  <% @tasks.each do |task| %>
    <li><input type="checkbox" value="1" name="task[completed]" id="task_completed" <%= task.completed ? "checked": "" %> disabled>


      <%= task.title %>
    <!-- <p><%= task.details %></p> -->
    <%= link_to "See specific task", task_path(task.id) %>
    </li>
 <%= link_to "Delete task", delete_task_path(task.id), method:"delete" %>
  <% end %>
</ul>
<br>
<p>but perhaps you want to create a new task</p>
 <%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= render 'form', task: @task %>



<%= link_to "Back to tasks", tasks_path %>

app/views/tasks/show.html.erb
<!-- app/views/tasks/show.html.erb -->
<h1>My Tasks</h1>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
 <%= link_to "Edit task", edit_task_path %>
 <%= link_to "Go back to list", tasks_path %>